# Generated by Django 6.0.4 on 2026-06-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('idAtividade', models.AutoField(primary_key=True, serialize=False)),
                ('nmAtividade', models.CharField(max_length=255)),
                ('descAtividade', models.TextField()),
                ('dtAtividade', models.DateField()),
            ],
            options={
                'db_table': 'atividade',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.AutoField(primary_key=True, serialize=False)),
                ('dtNoticia', models.DateField()),
                ('titulo', models.CharField(max_length=255)),
                ('desc_noticia', models.TextField()),
                ('flenvio', models.BooleanField()),
            ],
            options={
                'db_table': 'noticia',
            },
        ),
    ]
