# Generated by Django 6.0.4 on 2026-06-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='dtNoticia',
            new_name='dtnoticia',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='idNoticia',
            new_name='idnoticia',
        ),
    ]
