# Generated by Django 6.0.4 on 2026-06-05 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_rename_dtnoticia_noticia_dtnoticia_and_more'),
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='idturma',
            field=models.ForeignKey(db_column='idturma', default=1, on_delete=django.db.models.deletion.CASCADE, to='turma.turma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='flenvio',
            field=models.BooleanField(default=False),
        ),
    ]
