# Generated by Django 6.0.4 on 2026-06-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('num_telefone', models.CharField(max_length=20, unique=True)),
                ('nmaluno', models.CharField(max_length=20, unique=True)),
                ('flstatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'aluno',
            },
        ),
    ]
