# Generated by Django 6.0.4 on 2026-06-18 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='idturma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='turma.turma'),
        ),
    ]
