# Generated by Django 6.0.4 on 2026-05-13 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodo_letivo', '0002_alter_periodoletivo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteCurricular',
            fields=[
                ('idcompcurricular', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=255)),
                ('nmcompcurricular', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('idperiodoletivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodo_letivo.periodoletivo')),
            ],
            options={
                'db_table': 'public.comp_curricular',
            },
        ),
    ]
