# Generated by Django 6.0.4 on 2026-05-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp_curricular', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='componentecurricular',
            table='comp_curricular',
        ),
    ]
