# Generated by Django 6.0.4 on 2026-06-05 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comp_curricular', '0002_alter_componentecurricular_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('idturma', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.IntegerField()),
                ('flstatus', models.BooleanField(default=True)),
                ('idcompcurricular', models.ForeignKey(db_column='idcompcurricular', on_delete=django.db.models.deletion.CASCADE, to='comp_curricular.componentecurricular')),
            ],
            options={
                'db_table': 'turma',
            },
        ),
    ]
