# Generated by Django 6.0.4 on 2026-05-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoLetivo',
            fields=[
                ('idperiodoletivo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nmperiodo', models.CharField(max_length=255)),
                ('dtinicial', models.DateField()),
                ('dtfinal', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
