# Generated by Django 6.0.4 on 2026-05-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodo_letivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='periodoletivo',
            table='public.periodo_letivo',
        ),
    ]
