# Generated by Django 6.0.4 on 2026-05-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodo_letivo', '0002_alter_periodoletivo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='periodoletivo',
            table='periodo_letivo',
        ),
    ]
