# Generated by Django 6.0.4 on 2026-06-17 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram', models.BigIntegerField(help_text='ID interno do chat/grupo no Telegram', unique=True)),
                ('link_convite', models.URLField(blank=True, max_length=500, null=True)),
                ('total_membros', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('turma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_group', to='turma.turma')),
            ],
            options={
                'verbose_name': 'Grupo Telegram',
                'verbose_name_plural': 'Grupos Telegram',
            },
        ),
        migrations.CreateModel(
            name='TelegramAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MSG', 'Envio de Mensagem'), ('GRP', 'Criação de Grupo'), ('USR', 'Entrada de Usuário')], max_length=3)),
                ('descricao', models.TextField()),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('sucesso', models.BooleanField(default=True)),
                ('telegram_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='telegram.telegramgroup')),
            ],
            options={
                'verbose_name': 'Log do Telegram',
                'verbose_name_plural': 'Logs do Telegram',
                'ordering': ['-data_evento'],
            },
        ),
    ]
